-- schema
DROP SCHEMA IF EXISTS TR_OUTBOX CASCADE;
CREATE SCHEMA TR_OUTBOX;

-- dedup table for processed events
DROP TABLE IF EXISTS TR_OUTBOX.DEDUP_STORE CASCADE;
CREATE TABLE TR_OUTBOX.DEDUP_STORE (
    ID UUID NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PROCESSED_AT TIMESTAMP WITH TIME ZONE,
    PAYLOAD JSONB NOT NULL,
    CONSTRAINT PK_DEDUP PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TR_OUTBOX.EVENT_OUTBOX CASCADE;
CREATE TABLE TR_OUTBOX.EVENT_OUTBOX (
    ID UUID NOT NULL,
    PAYLOAD JSONB NOT NULL,
    DISPATCHED_AT TIMESTAMP WITH TIME ZONE,
    DESTINATION varchar(255) NULL,
    VERSION INTEGER NOT NULL,
    CONSTRAINT PK_EVENT_OUTBOX PRIMARY KEY (ID)
);