version: '3.9'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=EVENT_STORE
    networks:
      - ${INTERNAL_NETWORK:-postgres}